Sending exact asset where vulnerability found
Ostorlab/agent_tsunami pull request #31
Opened 2022-10-18 15:42 UTC by oussamaessaji

2022-10-19 15:24 UTC, deadly-panda commented on tests/agent_test.py
> +                                                          asset=domain_asset.DomainName(name='https://ostorlab.co')
If you are using DomainName asset, then i expect the name to be a domainname, not a link. you add the link as part of the metadata.

2022-10-19 15:25 UTC, deadly-panda commented on tests/agent_test.py
> +                                                          asset=domain_asset.DomainName(name='https://ostorlab.co')
If you are using DomainName asset, then i expect the name to be a domain name, not a link.
You can add the link as part of the metadata.

2022-10-19 15:41 UTC, deadly-panda requested changes

2022-10-19 15:41 UTC, deadly-panda commented on tests/agent_test.py
> +                                                          asset=domain_asset.DomainName(name='https://ostorlab.co')
If you are using DomainName asset, then i expect the name to be a domain name, not a link.
You can add the link as part of the metadata.

2022-10-19 15:41 UTC, deadly-panda commented on tests/agent_test.py
> +from ostorlab.assets import ipv4 as ipv4_asset
Please respect the guidlines we use for the imports, standard library /n 3rd party packages /n your code in other files.

2022-10-19 15:41 UTC, deadly-panda commented on tests/agent_test.py
> +    assert ['ipv4'] in [list(a.data.get('vulnerability_location', {}).keys()) for a in agent_mock]
Just prepare the full vuln location dict and check if it is part of the sent data.

2022-10-19 15:41 UTC, deadly-panda commented on tests/conftest.py
> +    return message.Message.from_data(selector, data=msg_data)
```suggestion
    return message.Message.from_data(selector, data=msg_data)

```

2022-10-19 15:41 UTC, deadly-panda commented on tests/agent_test.py
> +                                                          asset=domain_asset.DomainName(name='https://ostorlab.co')
same here

2022-10-19 15:41 UTC, deadly-panda commented on agent/tsunami_agent.py
> +    def _get_vuln_location(self, target):
add the types please

2022-10-19 15:41 UTC, deadly-panda commented on agent/tsunami_agent.py
> +            asset = domain_asset.DomainName(name=target.domain)
This should be the hostname, parsed_url.hostname

2022-10-19 15:41 UTC, deadly-panda commented on agent/tsunami/tsunami.py
> +                return f'--ip-v6-target={target.address}'
nice catch!

2022-10-20 10:38 UTC, 3asm approved these changes

2022-10-21 01:52 UTC, 3asm requested changes

2022-10-21 01:52 UTC, 3asm commented on agent/tsunami_agent.py
> +            else:
asset should be domain, not link.

2022-10-21 01:52 UTC, 3asm commented on agent/tsunami_agent.py
> +            else:
And metadata should have the URL.

2022-10-25 08:46 UTC, 3asm approved these changes

2022-10-25 08:46 UTC, merged